# Generated by Django 6.0.3 on 2026-03-21 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='duracao',
            field=models.IntegerField(blank=True, help_text='Duração em minutos', null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='nota_media',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='filmes.filme')),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(related_name='filmes', to='filmes.genero'),
        ),
    ]
